### ISSUE TITLE
Can't Install tess3r

### ISSUE THREAD

**Issue by nperry44** [bcm-uga/TESS3_encho_sen#10]
Hello,
I've been trying to install this package, but have been running into an error. I am working in R 3.5.1 on a windows machine, with Rtools 35 installed as well. I also have devtools installed. However, when I run:

devtools::install_github("bcm-uga/TESS3_encho_sen")

I get:

Downloading GitHub repo bcm-uga/TESS3_encho_sen@master
from URL https://api.github.com/repos/bcm-uga/TESS3_encho_sen/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing tess3r
"C:/Users/nperry/Desktop/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/nperry/AppData/Local/Temp/RtmpCWoBCw/devtools219c62a84714/bcm-uga-TESS3_encho_sen-43e5ede"  \
  --library="C:/Users/nperry/Desktop/R-3.5.1/library" --install-tests 

* installing *source* package 'tess3r' ...
** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'tess3r'
* removing 'C:/Users/nperry/Desktop/R-3.5.1/library/tess3r'
In R CMD INSTALL
Installation failed: Command failed (1)

Does anyone know how to fix this?

**Comment by olaas** [comment]
Hi!
Did you solve this problem?

**Comment by francoio** [comment]
hi 

It seems that the issue is not with tess3r but here: 

Please download and install the appropriate version of Rtools from [ http://cran.r-project.org/bin/windows/Rtools/ | http://cran.r-project.org/bin/windows/Rtools/ ] . 

I've not been using windows for scientific computing for a while. I'd recommend compiling tess3r on a linux or a macos system, it is easier. 

best wishes 
olivier 


De: "olaas" <notifications@github.com> 
À: "bcm-uga/TESS3_encho_sen" <TESS3_encho_sen@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mardi 16 Juillet 2019 10:36:40 
Objet: Re: [bcm-uga/TESS3_encho_sen] Can't Install tess3r (#10) 



Hi! 
Did you solve this problem?

**Comment by olaas** [comment]
Hi,

I'm not using Windows as well. Had this problem on Mac

wt., 16 lip 2019 o 10:48 Olivier Francois <notifications@github.com>
napisał(a):

**Comment by francoio** [comment]
so, it is a different problem. Rtools in windows only. 

Please, clarify what the message error is, or read the thread on " Installation issue: unsupported option '-fopenmp' " 



De: "olaas" <notifications@github.com> 
À: "bcm-uga/TESS3_encho_sen" <TESS3_encho_sen@noreply.github.com> 
Cc: "Olivier Francois" <olivier.francois@imag.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Mardi 16 Juillet 2019 10:59:07 
Objet: Re: [bcm-uga/TESS3_encho_sen] Can't Install tess3r (#10) 

Hi, 

I'm not using Windows as well. Had this problem on Mac 

wt., 16 lip 2019 o 10:48 Olivier Francois <notifications@github.com> 
napisał(a):

**Comment by olaas** [comment]
the error message is

* installing *source* package ‘tess3r’ ...
** libs
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG
-fopenmp
-I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include"
-I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppEigen/include"
-I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o
RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘tess3r’
* removing
‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tess3r’
Error in i.p(...) :
  (converted from warning) installation of package
‘/var/folders/r7/2plspwsx66v5k26wtjcm77jh0000gp/T//RtmpAy7a6K/file44ae4511a55c/tess3r_1.1.0.tar.gz’
had non-zero exit status

wt., 16 lip 2019 o 11:05 Olivier Francois <notifications@github.com>
napisał(a):

**Comment by francoio** [comment]
This the "clang: error: unsupported option '-fopenmp' " 

see the discussions at the end of the github issues thread on "Installation issue: unsupported option '-fopenmp' " . They solve this problem. You might need lgfortan too 

best wishes 
olivier 



De: "olaas" <notifications@github.com> 
À: "bcm-uga/TESS3_encho_sen" <TESS3_encho_sen@noreply.github.com> 
Cc: "Olivier Francois" <olivier.francois@imag.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Mardi 16 Juillet 2019 11:26:21 
Objet: Re: [bcm-uga/TESS3_encho_sen] Can't Install tess3r (#10) 

the error message is 

* installing *source* package ‘tess3r’ ... 
** libs 
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG 
-fopenmp 
-I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" 
-I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppEigen/include" 
-I/usr/local/include -fPIC -Wall -g -O2 -c RcppExports.cpp -o 
RcppExports.o 
clang: error: unsupported option '-fopenmp' 
make: *** [RcppExports.o] Error 1 
ERROR: compilation failed for package ‘tess3r’ 
* removing 
‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tess3r’ 
Error in i.p(...) : 
(converted from warning) installation of package 
‘/var/folders/r7/2plspwsx66v5k26wtjcm77jh0000gp/T//RtmpAy7a6K/file44ae4511a55c/tess3r_1.1.0.tar.gz’ 
had non-zero exit status 

wt., 16 lip 2019 o 11:05 Olivier Francois <notifications@github.com> 
napisał(a):
